#!/usr/bin/env bash
# sync-design-palette-wiki.sh
#
# Extracts color tokens from site.css (:root dark + [data-theme="light"])
# and pushes an auto-generated Design-Palette wiki page to the plugin repo.
# Called by the pipeline after any site.css change, or manually via:
#   make sync-palette-wiki
#
# Requires: gh CLI authenticated, git, grep, sed

set -euo pipefail

SITE_CSS="${1:-site.css}"
WIKI_REPO="mdeguzis/decky-proton-pulse"
WIKI_DIR=$(mktemp -d)
PAGE="Design-Palette.md"

trap 'rm -rf "$WIKI_DIR"' EXIT

echo "Extracting tokens from $SITE_CSS..."

# Pull dark-mode tokens from :root block
extract_root_tokens() {
  sed -n '/:root {/,/^}/p' "$SITE_CSS" \
    | grep -E '^\s+--' \
    | sed 's/;.*//' \
    | sed 's/^\s*//' \
    | while IFS=: read -r name value; do
        name=$(echo "$name" | xargs)
        value=$(echo "$value" | xargs)
        echo "| \`$name\` | \`$value\` |"
      done
}

# Pull light-mode overrides from [data-theme="light"] block
extract_light_tokens() {
  sed -n '/\[data-theme="light"\] {/,/^}/p' "$SITE_CSS" \
    | grep -E '^\s+--' \
    | sed 's/;.*//' \
    | sed 's/^\s*//' \
    | while IFS=: read -r name value; do
        name=$(echo "$name" | xargs)
        value=$(echo "$value" | xargs)
        echo "| \`$name\` | \`$value\` |"
      done
}

DARK_TOKENS=$(extract_root_tokens)
LIGHT_TOKENS=$(extract_light_tokens)
GENERATED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

cat > "$WIKI_DIR/$PAGE" <<WIKI_EOF
# Design Palette

> Auto-generated from \`site.css\` on $GENERATED_AT by \`scripts/sync-design-palette-wiki.sh\`.
> Do not edit this page directly - edit site.css and re-run the sync.

Single source of truth for colors, typography, and layout across the Proton
Pulse webui and Decky plugin UI. The main theming file is **site.css** in the
proton-pulse-web repo. All colors are CSS custom properties defined in
\`:root\` (dark, default) and overridden under \`[data-theme="light"]\`.

## Dark palette (default)

| Token | Value |
|-------|-------|
$DARK_TOKENS

## Light palette override

Only color tokens - layout tokens stay in \`:root\` since they don't change
between themes.

| Token | Value |
|-------|-------|
$LIGHT_TOKENS

## Palette philosophy

Dark, technical, gaming-adjacent. Two rules drive every color choice:

1. **Distinctness.** Functional surfaces (rating tiers, confidence, source
   pills) must read as their own thing at a glance. Never let a confidence
   pill share a hue with a rating badge.
2. **Restraint.** Bright accent colors are signals, not decoration. Default
   surface is dark blue-grey; saturated color only fires when there's
   something worth pointing at.

## Rating tier colors (badge-only)

These belong to per-report rating badges only. Never use them for confidence
or other surfaces.

| Tier | BG | Text |
|------|----|------|
| Platinum | \`#b4c7dc\` | \`#111\` |
| Gold | \`#c8a050\` | \`#111\` |
| Silver | \`#8fa0b0\` | \`#111\` |
| Bronze | \`#b07040\` | \`#fff\` |
| Borked | \`#c85050\` | \`#fff\` |

## Confidence pill (cyan-graded)

Always in the cyan family so it never collides with a tier color.

| Range | BG | Text |
|-------|----|------|
| 80-100% | \`#66c0f4\` | \`#0a1a24\` |
| 60-79% | \`#4a90b8\` | \`#0a1a24\` |
| 40-59% | \`#3a6680\` | \`#e8f4ff\` |
| 0-39% | \`#4a5a6a\` | \`#e8f4ff\` |

## Typography

| Token | Stack | Use |
|-------|-------|-----|
| \`--font-display\` | Space Grotesk, system-ui | titles, headings |
| \`--font-body\` | Inter, system-ui | body text |
| \`--mono\` | JetBrains Mono, monospace | code, IDs, numbers |

## Layout principles

- Clean over clever. Sparse layouts beat dense ones.
- One signal per surface. A card has one rating badge, one confidence pill.
- Borders are joins, not decoration.
- Don't ship a hex value that isn't in this file or a \`var(--token)\`.

---
*Generated by the proton-pulse-web pipeline. Source: \`site.css\` + \`scripts/sync-design-palette-wiki.sh\`*
WIKI_EOF

echo "Pushing to wiki..."
cd "$WIKI_DIR"
git clone --depth 1 "git@github.com:${WIKI_REPO}.wiki.git" wiki 2>/dev/null
cp "$PAGE" wiki/
cd wiki
git add "$PAGE"
if git diff --cached --quiet; then
  echo "No changes to wiki page."
else
  git commit -m "Auto-sync Design Palette from site.css ($GENERATED_AT)"
  git push
  echo "Wiki page updated."
fi
